spring:
  application:
    name: graphql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/project

server:
  port: 8082


